version: '3.9'

services:
  top-api:
    build: .
    container_name: top-api
    restart:  on-failure
    env_file:
      - .env
    ports:
      - '3000:3000'
    networks:
      - mongo_network

networks:
  mongo_network:
    name: mongo_default
    external: true
